/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/account/Settings': RouteRecordInfo<'/account/Settings', '/account/Settings', Record<never, never>, Record<never, never>>,
    '/admin/rosters/RosterList': RouteRecordInfo<'/admin/rosters/RosterList', '/admin/rosters/RosterList', Record<never, never>, Record<never, never>>,
    '/admin/team/[Id]': RouteRecordInfo<'/admin/team/[Id]', '/admin/team/:Id', { Id: ParamValue<true> }, { Id: ParamValue<false> }>,
    '/admin/team/CreateTeam': RouteRecordInfo<'/admin/team/CreateTeam', '/admin/team/CreateTeam', Record<never, never>, Record<never, never>>,
    '/admin/team/TeamList': RouteRecordInfo<'/admin/team/TeamList', '/admin/team/TeamList', Record<never, never>, Record<never, never>>,
    '/admin/users/[Id]': RouteRecordInfo<'/admin/users/[Id]', '/admin/users/:Id', { Id: ParamValue<true> }, { Id: ParamValue<false> }>,
    '/admin/users/CreateUser': RouteRecordInfo<'/admin/users/CreateUser', '/admin/users/CreateUser', Record<never, never>, Record<never, never>>,
    '/admin/users/UsersList': RouteRecordInfo<'/admin/users/UsersList', '/admin/users/UsersList', Record<never, never>, Record<never, never>>,
    '/auth/SignIn': RouteRecordInfo<'/auth/SignIn', '/auth/SignIn', Record<never, never>, Record<never, never>>,
    '/errorPages/NotFound': RouteRecordInfo<'/errorPages/NotFound', '/errorPages/NotFound', Record<never, never>, Record<never, never>>,
    '/errorPages/Unauthorized': RouteRecordInfo<'/errorPages/Unauthorized', '/errorPages/Unauthorized', Record<never, never>, Record<never, never>>,
    '/managers/rosters/RosterList': RouteRecordInfo<'/managers/rosters/RosterList', '/managers/rosters/RosterList', Record<never, never>, Record<never, never>>,
    '/managers/team/TeamPage': RouteRecordInfo<'/managers/team/TeamPage', '/managers/team/TeamPage', Record<never, never>, Record<never, never>>,
  }
}
