/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account/Settings': RouteRecordInfo<'/account/Settings', '/account/Settings', Record<never, never>, Record<never, never>>,
    '/errorPages/NotFound': RouteRecordInfo<'/errorPages/NotFound', '/errorPages/NotFound', Record<never, never>, Record<never, never>>,
    '/rosters/RosterList': RouteRecordInfo<'/rosters/RosterList', '/rosters/RosterList', Record<never, never>, Record<never, never>>,
    '/team/[Id]': RouteRecordInfo<'/team/[Id]', '/team/:Id', { Id: ParamValue<true> }, { Id: ParamValue<false> }>,
    '/team/CreateTeam': RouteRecordInfo<'/team/CreateTeam', '/team/CreateTeam', Record<never, never>, Record<never, never>>,
    '/team/TeamList': RouteRecordInfo<'/team/TeamList', '/team/TeamList', Record<never, never>, Record<never, never>>,
    '/users/[Id]': RouteRecordInfo<'/users/[Id]', '/users/:Id', { Id: ParamValue<true> }, { Id: ParamValue<false> }>,
    '/users/CreateUser': RouteRecordInfo<'/users/CreateUser', '/users/CreateUser', Record<never, never>, Record<never, never>>,
    '/users/UsersList': RouteRecordInfo<'/users/UsersList', '/users/UsersList', Record<never, never>, Record<never, never>>,
  }
}
