export const icons = {
    saveIcon: 'mdi-bookmark',
    editIcon: 'mdi-pencil',
    inactiveIcon: 'mdi-trash-can',
    activeIcon: 'mdi-check-bold',
    addIcon: 'mdi-plus',
    listIcon: 'mdi-list-box-outline',
    infoIcon: 'mdi-information-outline',
    leftArrow: 'mdi-arrow-left',
    rightArrow: 'mdi-arrow-right',
    uploadIcon: 'mdi-upload',
    closeIcon: 'mdi-close',
    locationIcon: 'mdi-map-marker',
    emailIcon: 'mdi-email',
    phoneIcon: 'mdi-phone',
    roleIcon: 'mdi-shield-account',
    sentByIcon: 'mdi-email-check',
    sentOnIcon: 'mdi-calendar-check-outline',
    moveOutIcon: 'mdi-export',
    currencyIcon: 'mdi-currency-usd',
}